baseURL = 'https://zatools.kb10uy.dev/'
languageCode = 'ja-jp'
title = 'kb10uy-zatools'

theme = 'geekdoc'

pluralizeListTitles = false

pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

enableRobotsTXT = true

[markup]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1
endLevel = 9

[taxonomies]
tag = "tags"
