title = "kb10uy's Various Tools"
baseURL = "https://zatools.kb10uy.dev/"
languageCode = "ja-jp"
theme = "relearn"

enableRobotsTXT = true

[markup]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
startLevel = 1
endLevel = 9

[taxonomies]
tag = "tags"

[params]
themeVariant = ["relearn-dark", "relearn-light"]
